AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an S3 bucket with public access, static web hosting, and a specific bucket policy.

Parameters:
  BucketName:
    Description: Name of the S3 bucket
    Type: String
  Region:
    Description: AWS Region for the S3 bucket
    Type: String
    AllowedValues:
      - us-east-1
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-central-1
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - ap-northeast-2
      - sa-east-1
      - ca-central-1
      - cn-north-1
      - cn-northwest-1
      - eu-west-2
      - eu-west-3
      - eu-north-1
      - ap-south-1
      - me-south-1
      - af-south-1
    Default: us-east-1

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource:
              - !Sub "arn:aws:s3:::${BucketName}/*"

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
  BucketWebsiteURL:
    Description: URL of the S3 bucket website
    Value: !GetAtt S3Bucket.WebsiteURL
