AWSTemplateFormatVersion: 2010-09-09

Resources:
  # SNS Topic
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: content-analysis-sagemaker
      DisplayName: Content Analysis Endpoint Topic

  # SageMaker Endpoint Configuration
  AsyncEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      EndpointConfigName: async-endpoint
      AsyncInferenceConfig:
        OutputConfig:
          S3OutputPath: s3://tiktok-clone-sagemaker/content-analysis/outputs
          S3FailurePath: s3://tiktok-clone-sagemaker/content-analysis/failures
          NotificationConfig:
            SuccessTopic: !Ref SNSTopic
            ErrorTopic: !Ref SNSTopic
      ProductionVariants:
        - VariantName: AllTraffic
          ModelName: content-analysis # Replace with actual model name
          InitialInstanceCount: 0
          InstanceType: ml.m5.xlarge
          InitialVariantWeight: 1

  # SageMaker Endpoint
  Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointName: content-analysis
      EndpointConfigName: !Ref AsyncEndpointConfig

Outputs:
  OutputBucketName:
    Description: Name of the output bucket
    Value: !Ref OutputBucket

  FailureBucketName:
    Description: Name of the failure bucket
    Value: !Ref FailureBucket

  SNSTopicARN:
    Description: ARN of the SNS Topic
    Value: !Ref SNSTopic
Transform: AWS::Serverless-2016-10-31